# Generated by Django 5.1.5 on 2025-01-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
