# Generated by Django 5.1.5 on 2025-01-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilephone",
            name="network_2g_bands",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mobilephone",
            name="network_3g_bands",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mobilephone",
            name="network_4g_bands",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mobilephone",
            name="network_5g_bands",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mobilephone",
            name="network_speed",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
