# Generated by Django 5.1.5 on 2025-01-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_order_customer_order_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobilephone",
            name="storage",
        ),
    ]
