# Generated by Django 5.1.5 on 2025-01-15 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_mobilephone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='announcement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='battery_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='build',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='camera_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='card_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='charging',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='display_protection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='display_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='display_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='gpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='internal_memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='jack_3_5mm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='main_camera',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='network_bands',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='nfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='positioning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='price_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='selfie_camera',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='selfie_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='sensors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='speaker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='usb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='water_resistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='wlan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='mobile_phone_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='chipset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
