# Generated by Django 5.1.5 on 2025-01-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_mobilephone_storage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilephone",
            old_name="usb",
            new_name="usb_type",
        ),
        migrations.RemoveField(
            model_name="mobilephone",
            name="build",
        ),
        migrations.RemoveField(
            model_name="mobilephone",
            name="camera",
        ),
        migrations.RemoveField(
            model_name="mobilephone",
            name="display",
        ),
        migrations.RemoveField(
            model_name="mobilephone",
            name="usb_type_c",
        ),
    ]
