# Generated by Django 5.1.5 on 2025-01-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_mobilephone_announcement_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='store.category')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='store.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('graphics_card', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_life', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('wifi', models.BooleanField(default=True)),
                ('bluetooth', models.BooleanField(default=True)),
                ('usb_type_c', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='store.category')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='store.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('battery_capacity', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
                ('sim_support', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('wifi', models.BooleanField(default=True)),
                ('bluetooth', models.BooleanField(default=True)),
                ('usb_type_c', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablets', to='store.category')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablets', to='store.shopowner')),
            ],
        ),
    ]
