# Generated by Django 5.1.5 on 2025-01-22 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_laptop_display_remove_laptop_operating_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, message="Review must be at least 10 characters long."
                    )
                ]
            ),
        ),
    ]
