# Generated by Django 5.1.5 on 2025-01-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_cart_customer_cart_updated_at_customer_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
