# Generated by Django 5.1.5 on 2025-01-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_image_created_at_image_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
