# Generated by Django 5.1.5 on 2025-01-16 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_review_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.laptop'),
        ),
        migrations.AlterField(
            model_name='review',
            name='mobile_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.mobilephone'),
        ),
    ]
