# Generated by Django 5.1.5 on 2025-01-16 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='mobile_phone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='store.mobilephone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
