# Generated by Django 5.1.5 on 2025-01-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_accessory_mobile_phone_alter_accessory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='mobile_phone',
        ),
    ]
