# Generated by Django 5.1.5 on 2025-01-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.accessory'),
        ),
    ]
