# Generated by Django 5.1.5 on 2025-01-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_review_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='mobile_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='store.mobilephone'),
        ),
    ]
