# Generated by Django 5.1.5 on 2025-01-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='store.laptop'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='mobile_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='store.mobilephone'),
        ),
    ]
